[package]
name = "shape-blast"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor = { path = "../anchor" }
lyon = "1.0" 
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }
sparsey = "0.11"
